"""Regenerate ``examples/cap_0402_100nF_series.s2p`` deterministically (DESIGN.md §4.5).

Synthetic series-through Touchstone v1 file computed from ``examples/cap_0402_100nF.mod`` with the
package's own SPICE parser and MNA solver: Z0 = 50 Ω, 1 kHz–3 GHz, 201 log-spaced points,
``# HZ S RI R 50``. S21 = S12 = 2·Z0/(2·Z0 + Z), S11 = S22 = Z/(2·Z0 + Z) (§2.7.2).

Usage: ``python tools/make_example_s2p.py``
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from simple_pi_calculator.core.mna import impedance_two_terminal  # noqa: E402
from simple_pi_calculator.core.spice_parser import parse_spice_file  # noqa: E402
from simple_pi_calculator.errors import IssueCollector  # noqa: E402

Z0 = 50.0
F_START_HZ = 1e3
F_STOP_HZ = 3e9
N_POINTS = 201


def build_text() -> str:
    issues = IssueCollector()
    netlist = parse_spice_file(ROOT / "examples" / "cap_0402_100nF.mod", None, issues)
    f = np.logspace(np.log10(F_START_HZ), np.log10(F_STOP_HZ), N_POINTS)
    z = impedance_two_terminal(netlist, f)
    s21 = 2 * Z0 / (2 * Z0 + z)
    s11 = z / (2 * Z0 + z)
    lines = [
        "! Simple PI Calculator example (synthetic, not measured data)",
        "! 0.1 uF 0402 series R-L-C (R = 30 mOhm, L = 0.45 nH, C = 100 nF), series-through fixture",
        "! generated by tools/make_example_s2p.py from examples/cap_0402_100nF.mod",
        "! f  S11(re im)  S21(re im)  S12(re im)  S22(re im)",
        "# HZ S RI R 50",
    ]
    for fi, a, b in zip(f, s11, s21):
        vals = [a.real, a.imag, b.real, b.imag, b.real, b.imag, a.real, a.imag]
        lines.append(f"{fi:.10e} " + " ".join(f"{v:.16e}" for v in vals))
    return "\n".join(lines) + "\n"


def main() -> None:
    out = ROOT / "examples" / "cap_0402_100nF_series.s2p"
    out.write_text(build_text(), encoding="utf-8", newline="\n")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
