"""Write the PyInstaller Windows version resource (DESIGN.md §7.3).

Usage: ``python tools/write_version_info.py packaging/version_info.txt``

The version comes from ``src/simple_pi_calculator/__init__.py`` (single source of truth); it is
read with a regular expression so the package does not need to be importable.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
INIT = ROOT / "src" / "simple_pi_calculator" / "__init__.py"

TEMPLATE = """# UTF-8
# Generated by tools/write_version_info.py - do not edit.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=({v0}, {v1}, {v2}, 0),
    prodvers=({v0}, {v1}, {v2}, 0),
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable(
        '040904B0',
        [StringStruct('CompanyName', 'Simple PI Calculator contributors'),
         StringStruct('FileDescription', 'Simple PI Calculator'),
         StringStruct('FileVersion', '{version}.0'),
         StringStruct('InternalName', 'SimplePICalculator'),
         StringStruct('LegalCopyright', 'Copyright (c) 2026 Simple PI Calculator contributors. MIT License.'),
         StringStruct('OriginalFilename', 'SimplePICalculator.exe'),
         StringStruct('ProductName', 'Simple PI Calculator'),
         StringStruct('ProductVersion', '{version}')])
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
"""


def read_version(init_path: Path = INIT) -> str:
    match = re.search(r'^__version__\s*=\s*["\']([^"\']+)["\']', init_path.read_text("utf-8"), re.M)
    if not match:
        raise SystemExit(f"__version__ not found in {init_path}")
    return match.group(1)


def render(version: str) -> str:
    core = re.match(r"^(\d+)\.(\d+)\.(\d+)", version)
    if not core:
        raise SystemExit(f"version {version!r} is not SemVer X.Y.Z")
    v0, v1, v2 = core.groups()
    return TEMPLATE.format(v0=int(v0), v1=int(v1), v2=int(v2), version=f"{v0}.{v1}.{v2}")


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        print(__doc__)
        return 2
    out = Path(argv[1])
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render(read_version()), encoding="utf-8")
    print(f"wrote {out} (version {read_version()})")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
